apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: gmacastil/micro-dolar
    sonarqube.org/project-key: micro-dolar
  description: "Aplicaci\xF3n en Java para c\xE1lculos relacionados con el d\xF3lar\
    \ utilizando Spring."
  name: micro-dolar
  tags:
  - java
  - spring
spec:
  lifecycle: production
  owner: gmacastil
  system: dummy
  type: service
