apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: gmacastil/micro-dolar
    sonarqube.org/project-key: micro-dolar
  description: Aplicación en Java para cálculos relacionados con el dólar utilizando
    Spring.
  name: micro-dolar
  tags:
  - java
  - spring
spec:
  lifecycle: production
  owner: gmacastil
  system: dummy
  type: service
